#pragma once

#include "Application.h"
#include "ArkEngine.h"
#include "Input/InputManager.h"
#include "Graphics/ShaderProgram.h"
#include "Graphics/GraphicsAPI.h"
#include "Graphics/VertexLayout.h"
#include "Graphics/Texture.h"
#include "Render/Material.h"
#include "Render/Mesh.h"
#include "Render/RenderQueue.h"
#include "Scene/GameObject.h"
#include "Scene/Scene.h"
#include "Scene/Component.h"
#include "Scene/Components/MeshComponent.h"
#include "Scene/Components/CameraComponent.h"
#include "Scene/Components/PlayerControllerComponent.h"
#include "Scene/Components/LightComponent.h"
#include "Scene/Components/AnimationComponent.h"
#include "Scene/Components/PhysicsComponent.h"
#include "Scene/Components/AudioComponent.h"
#include "Scene/Components/AudioListenerComponent.h"
#include "Scene/Components/SpriteComponent.h"
#include "Scene/Components/UI/CanvasComponent.h"
#include "Scene/Components/UI/TextComponent.h"
#include "Scene/Components/UI/UIElementComponent.h"
#include "Scene/Components/UI/UIInputSystem.h"
#include "Scene/Components/UI/ButtonComponent.h"
#include "Scene/Components/UI/UIImageComponent.h"
#include "Physics/Collider.h"
#include "Physics/RigidBody.h"
#include "Physics/PhysicsManager.h"
#include "Physics/KinematicCharacterController.h"
#include "Physics/CollisionObject.h"
#include "Audio/AudioManager.h"
#include "Audio/Audio.h"
#include "Font/FontManager.h"
#include "Font/Font.h"
#include "AssetManager/FileSystem.h"
// This header file serves as a central include for all core engine components, allowing other parts of the codebase to include this single file to access the entire engine functionality.

// By including this file, you can access all the core engine classes and functionalities without needing to include each header individually in your source files.
// Generally used in Game.cpp or actual game related source files to access the engine's features.